// ============================================================
// NIRIKSHAN AI — Demo Repository
// Prototype data only. Not official MPLADS records.
// ============================================================

// ── MPs ──────────────────────────────────────────────────────
const MPs = [
  { mp_id: 'MP001', name: 'Pralhad Venkatesh Joshi', constituency: 'Dharwad', state: 'Karnataka', house: 'Lok Sabha', party: 'BJP' },
  { mp_id: 'MP002', name: 'D. K. Suresh', constituency: 'Bengaluru Rural', state: 'Karnataka', house: 'Lok Sabha', party: 'INC' },
  { mp_id: 'MP003', name: 'Rajnath Singh', constituency: 'Lucknow', state: 'Uttar Pradesh', house: 'Lok Sabha', party: 'BJP' },
  { mp_id: 'MP004', name: 'Dimple Yadav', constituency: 'Mainpuri', state: 'Uttar Pradesh', house: 'Lok Sabha', party: 'SP' },
  { mp_id: 'MP005', name: 'Supriya Sule', constituency: 'Baramati', state: 'Maharashtra', house: 'Lok Sabha', party: 'NCP' },
  { mp_id: 'MP006', name: 'Eknath Shinde', constituency: 'Kalyan', state: 'Maharashtra', house: 'Lok Sabha', party: 'SS' },
  { mp_id: 'MP007', name: 'Kanimozhi', constituency: 'Thoothukudi', state: 'Tamil Nadu', house: 'Lok Sabha', party: 'DMK' },
  { mp_id: 'MP008', name: 'A. Raja', constituency: 'Nilgiris', state: 'Tamil Nadu', house: 'Lok Sabha', party: 'DMK' },
  { mp_id: 'MP009', name: 'Derek O Brien', constituency: 'West Bengal', state: 'West Bengal', house: 'Rajya Sabha', party: 'AITMC' },
  { mp_id: 'MP010', name: 'Mahua Moitra', constituency: 'Krishnanagar', state: 'West Bengal', house: 'Lok Sabha', party: 'AITMC' },
  { mp_id: 'MP011', name: 'Shashi Tharoor', constituency: 'Thiruvananthapuram', state: 'Kerala', house: 'Lok Sabha', party: 'INC' },
  { mp_id: 'MP012', name: 'V. Muraleedharan', constituency: 'Kerala', state: 'Kerala', house: 'Rajya Sabha', party: 'BJP' },
  { mp_id: 'MP013', name: 'Bhupender Yadav', constituency: 'Rajasthan', state: 'Rajasthan', house: 'Rajya Sabha', party: 'BJP' },
  { mp_id: 'MP014', name: 'Sachin Pilot', constituency: 'Tonk-Sawai Madhopur', state: 'Rajasthan', house: 'Lok Sabha', party: 'INC' },
  { mp_id: 'MP015', name: 'Smriti Irani', constituency: 'Amethi', state: 'Uttar Pradesh', house: 'Lok Sabha', party: 'BJP' },
];

const IDAs = [
  { ida_id: 'IDA-KA-01', name: 'District Collector, Dharwad', state: 'Karnataka', district: 'Dharwad' },
  { ida_id: 'IDA-KA-02', name: 'District Collector, Bengaluru Rural', state: 'Karnataka', district: 'Bengaluru Rural' },
  { ida_id: 'IDA-KA-03', name: 'District Collector, Belagavi', state: 'Karnataka', district: 'Belagavi' },
  { ida_id: 'IDA-UP-01', name: 'District Collector, Lucknow', state: 'Uttar Pradesh', district: 'Lucknow' },
  { ida_id: 'IDA-UP-02', name: 'District Collector, Mainpuri', state: 'Uttar Pradesh', district: 'Mainpuri' },
  { ida_id: 'IDA-MH-01', name: 'District Collector, Pune', state: 'Maharashtra', district: 'Pune' },
  { ida_id: 'IDA-MH-02', name: 'District Collector, Thane', state: 'Maharashtra', district: 'Thane' },
  { ida_id: 'IDA-TN-01', name: 'District Collector, Thoothukudi', state: 'Tamil Nadu', district: 'Thoothukudi' },
  { ida_id: 'IDA-TN-02', name: 'District Collector, The Nilgiris', state: 'Tamil Nadu', district: 'The Nilgiris' },
  { ida_id: 'IDA-WB-01', name: 'District Collector, Nadia', state: 'West Bengal', district: 'Nadia' },
  { ida_id: 'IDA-KL-01', name: 'District Collector, Thiruvananthapuram', state: 'Kerala', district: 'Thiruvananthapuram' },
  { ida_id: 'IDA-RJ-01', name: 'District Collector, Jaipur', state: 'Rajasthan', district: 'Jaipur' },
  { ida_id: 'IDA-RJ-02', name: 'District Collector, Tonk', state: 'Rajasthan', district: 'Tonk' },
];

const vendors = [
  { vendor_id: 'V001', name: 'Bharat Construction Pvt Ltd', type: 'Civil Works', state: 'Karnataka' },
  { vendor_id: 'V002', name: 'National Road Builders', type: 'Road Construction', state: 'Karnataka' },
  { vendor_id: 'V003', name: 'Laxmi Infratech', type: 'Civil Works', state: 'Uttar Pradesh' },
  { vendor_id: 'V004', name: 'Rajesh Constructions', type: 'Building Construction', state: 'Maharashtra' },
  { vendor_id: 'V005', name: 'Southern Bridge Works', type: 'Bridge & Culvert', state: 'Tamil Nadu' },
  { vendor_id: 'V006', name: 'KP Infrastructures', type: 'Water Supply', state: 'Kerala' },
  { vendor_id: 'V007', name: 'Ganesh Enterprises', type: 'Civil Works', state: 'Rajasthan' },
  { vendor_id: 'V008', name: 'Deccan Contractors', type: 'Multi-category', state: 'Karnataka' },
  { vendor_id: 'V009', name: 'Narmada Civil Works', type: 'Civil Works', state: 'Uttar Pradesh' },
  { vendor_id: 'V010', name: 'Prime Build India', type: 'Building Construction', state: 'West Bengal' },
  { vendor_id: 'V011', name: 'Saraswati Infra', type: 'Civil Works', state: 'Maharashtra' },
  { vendor_id: 'V012', name: 'Tamil Builders Co', type: 'Civil Works', state: 'Tamil Nadu' },
];

const calamities = [
  { calamity_id: 'CAL001', type: 'Flood', description: 'Severe flooding in North Karnataka (Aug 2024)', state: 'Karnataka', year: 2024, amount_consented_lakh: 500 },
  { calamity_id: 'CAL002', type: 'Cyclone', description: 'Cyclone Michaung impact on Tamil Nadu coast (Dec 2023)', state: 'Tamil Nadu', year: 2023, amount_consented_lakh: 350 },
  { calamity_id: 'CAL003', type: 'Flood', description: 'Monsoon floods in West Bengal (Jul 2024)', state: 'West Bengal', year: 2024, amount_consented_lakh: 280 },
  { calamity_id: 'CAL004', type: 'Drought', description: 'Severe drought conditions in Rajasthan (2023)', state: 'Rajasthan', year: 2023, amount_consented_lakh: 200 },
];

const worksRaw = [
  // Karnataka – MP001
  { internal_work_key: 'IWK-KA-001', official_work_id: null, mp_id: 'MP001', ida_id: 'IDA-KA-01', category: 'Road Construction', description: 'Construction of CC road from Dharwad Bus Stand to Railway Station', state: 'Karnataka', district: 'Dharwad', recommended_amount_lakh: 45.0, sanctioned_amount_lakh: 43.5, total_expenditure_lakh: 44.8, status: 'COMPLETED', recommended_date: '2022-06-10', sanctioned_date: '2022-08-15', first_expenditure_date: '2022-09-01', latest_expenditure_date: '2023-04-20', completion_date: '2023-04-25', calamity_id: null, vendor_ids: ['V002'] },
  { internal_work_key: 'IWK-KA-002', official_work_id: null, mp_id: 'MP001', ida_id: 'IDA-KA-01', category: 'Drinking Water Supply', description: 'Providing drinking water supply to Kalaghatagi village Phase II', state: 'Karnataka', district: 'Dharwad', recommended_amount_lakh: 28.0, sanctioned_amount_lakh: 27.5, total_expenditure_lakh: 27.5, status: 'COMPLETED', recommended_date: '2022-03-20', sanctioned_date: '2022-05-10', first_expenditure_date: '2022-06-01', latest_expenditure_date: '2023-01-15', completion_date: '2023-01-20', calamity_id: null, vendor_ids: ['V001'] },
  { internal_work_key: 'IWK-KA-003', official_work_id: null, mp_id: 'MP001', ida_id: 'IDA-KA-01', category: 'Community Hall', description: 'Construction of community hall at Kundagol Gram Panchayat', state: 'Karnataka', district: 'Dharwad', recommended_amount_lakh: 80.0, sanctioned_amount_lakh: 78.0, total_expenditure_lakh: 99.6, status: 'COMPLETED', recommended_date: '2021-09-05', sanctioned_date: '2021-11-20', first_expenditure_date: '2022-01-10', latest_expenditure_date: '2024-02-28', completion_date: '2024-03-05', calamity_id: null, vendor_ids: ['V008', 'V001'] },
  { internal_work_key: 'IWK-KA-004', official_work_id: null, mp_id: 'MP001', ida_id: 'IDA-KA-01', category: 'Road Construction', description: 'Widening and strengthening of road connecting Hubli-Dharwad bypass', state: 'Karnataka', district: 'Dharwad', recommended_amount_lakh: 120.0, sanctioned_amount_lakh: 118.0, total_expenditure_lakh: 87.0, status: 'ONGOING', recommended_date: '2023-04-10', sanctioned_date: '2023-07-01', first_expenditure_date: '2023-09-15', latest_expenditure_date: '2025-11-30', completion_date: null, calamity_id: null, vendor_ids: ['V002', 'V008'] },
  { internal_work_key: 'IWK-KA-005', official_work_id: null, mp_id: 'MP001', ida_id: 'IDA-KA-01', category: 'Flood Relief Infrastructure', description: 'Construction of flood protection bund at Alnavar village (calamity work)', state: 'Karnataka', district: 'Dharwad', recommended_amount_lakh: 60.0, sanctioned_amount_lakh: 58.5, total_expenditure_lakh: 41.2, status: 'ONGOING', recommended_date: '2024-09-10', sanctioned_date: '2024-10-05', first_expenditure_date: '2024-11-01', latest_expenditure_date: '2025-10-15', completion_date: null, calamity_id: 'CAL001', vendor_ids: ['V001'] },
  { internal_work_key: 'IWK-KA-006', official_work_id: null, mp_id: 'MP001', ida_id: 'IDA-KA-01', category: 'School Building', description: 'Construction of additional classrooms at Government Higher Primary School, Navalgund', state: 'Karnataka', district: 'Dharwad', recommended_amount_lakh: 30.0, sanctioned_amount_lakh: 29.5, total_expenditure_lakh: 29.2, status: 'COMPLETED', recommended_date: '2023-01-15', sanctioned_date: '2023-03-10', first_expenditure_date: '2023-05-01', latest_expenditure_date: '2024-01-20', completion_date: '2024-01-25', calamity_id: null, vendor_ids: ['V001'] },
  { internal_work_key: 'IWK-KA-007', official_work_id: null, mp_id: 'MP001', ida_id: 'IDA-KA-01', category: 'Road Construction', description: 'CC road construction from Kalaghatagi Main Road to Hanuman Temple', state: 'Karnataka', district: 'Dharwad', recommended_amount_lakh: 32.0, sanctioned_amount_lakh: 31.0, total_expenditure_lakh: 30.8, status: 'COMPLETED', recommended_date: '2022-11-05', sanctioned_date: '2023-01-20', first_expenditure_date: '2023-03-10', latest_expenditure_date: '2023-11-05', completion_date: '2023-11-10', calamity_id: null, vendor_ids: ['V002'] },
  { internal_work_key: 'IWK-KA-008', official_work_id: null, mp_id: 'MP001', ida_id: 'IDA-KA-01', category: 'Sanitation', description: 'Construction of public toilet complex at Dharwad bus terminal', state: 'Karnataka', district: 'Dharwad', recommended_amount_lakh: 18.5, sanctioned_amount_lakh: 18.0, total_expenditure_lakh: 18.0, status: 'COMPLETED', recommended_date: '2022-07-20', sanctioned_date: '2022-09-05', first_expenditure_date: '2022-10-01', latest_expenditure_date: '2023-03-10', completion_date: '2023-03-15', calamity_id: null, vendor_ids: ['V001'] },
  { internal_work_key: 'IWK-KA-009', official_work_id: null, mp_id: 'MP001', ida_id: 'IDA-KA-03', category: 'Bridge', description: 'Construction of minor bridge over Malaprabha river at Munavalli', state: 'Karnataka', district: 'Belagavi', recommended_amount_lakh: 95.0, sanctioned_amount_lakh: 93.0, total_expenditure_lakh: 94.5, status: 'ONGOING', recommended_date: '2022-08-10', sanctioned_date: '2022-11-01', first_expenditure_date: '2023-01-10', latest_expenditure_date: '2025-09-15', completion_date: null, calamity_id: null, vendor_ids: ['V008', 'V002'] },
  { internal_work_key: 'IWK-KA-010', official_work_id: null, mp_id: 'MP001', ida_id: 'IDA-KA-01', category: 'Community Hall', description: 'Renovation and expansion of gram panchayat community hall, Kalghatagi', state: 'Karnataka', district: 'Dharwad', recommended_amount_lakh: 42.0, sanctioned_amount_lakh: 41.0, total_expenditure_lakh: 12.5, status: 'ONGOING', recommended_date: '2025-02-10', sanctioned_date: '2025-04-15', first_expenditure_date: '2025-06-01', latest_expenditure_date: '2025-09-01', completion_date: null, calamity_id: null, vendor_ids: ['V001'] },
  // Karnataka – MP002
  { internal_work_key: 'IWK-KA-011', official_work_id: null, mp_id: 'MP002', ida_id: 'IDA-KA-02', category: 'Road Construction', description: 'Asphalting and improvement of Doddaballapur-Vijayanagara road', state: 'Karnataka', district: 'Bengaluru Rural', recommended_amount_lakh: 75.0, sanctioned_amount_lakh: 74.0, total_expenditure_lakh: 73.5, status: 'COMPLETED', recommended_date: '2022-04-20', sanctioned_date: '2022-06-15', first_expenditure_date: '2022-08-01', latest_expenditure_date: '2023-05-20', completion_date: '2023-05-28', calamity_id: null, vendor_ids: ['V002'] },
  { internal_work_key: 'IWK-KA-012', official_work_id: null, mp_id: 'MP002', ida_id: 'IDA-KA-02', category: 'Drinking Water Supply', description: 'Bore well and overhead tank at Nelamangala Gram Panchayat', state: 'Karnataka', district: 'Bengaluru Rural', recommended_amount_lakh: 22.0, sanctioned_amount_lakh: 21.5, total_expenditure_lakh: 21.3, status: 'COMPLETED', recommended_date: '2023-02-10', sanctioned_date: '2023-04-01', first_expenditure_date: '2023-06-01', latest_expenditure_date: '2023-12-20', completion_date: '2023-12-28', calamity_id: null, vendor_ids: ['V001'] },
  { internal_work_key: 'IWK-KA-013', official_work_id: null, mp_id: 'MP002', ida_id: 'IDA-KA-02', category: 'School Building', description: 'Construction of new school building at Government School, Hoskote', state: 'Karnataka', district: 'Bengaluru Rural', recommended_amount_lakh: 55.0, sanctioned_amount_lakh: 54.0, total_expenditure_lakh: 52.3, status: 'COMPLETED', recommended_date: '2021-11-15', sanctioned_date: '2022-01-20', first_expenditure_date: '2022-03-10', latest_expenditure_date: '2023-06-30', completion_date: '2023-07-05', calamity_id: null, vendor_ids: ['V008'] },
  { internal_work_key: 'IWK-KA-014', official_work_id: null, mp_id: 'MP002', ida_id: 'IDA-KA-02', category: 'Flood Relief Infrastructure', description: 'Reconstruction of damaged culverts at Doddaballapur calamity relief', state: 'Karnataka', district: 'Bengaluru Rural', recommended_amount_lakh: 38.0, sanctioned_amount_lakh: 37.0, total_expenditure_lakh: 47.2, status: 'COMPLETED', recommended_date: '2024-08-20', sanctioned_date: '2024-09-05', first_expenditure_date: '2024-09-20', latest_expenditure_date: '2025-01-30', completion_date: '2025-02-05', calamity_id: 'CAL001', vendor_ids: ['V002', 'V008'] },
  { internal_work_key: 'IWK-KA-015', official_work_id: null, mp_id: 'MP002', ida_id: 'IDA-KA-02', category: 'Anganwadi', description: 'Construction of Anganwadi centre at Devanahalli village', state: 'Karnataka', district: 'Bengaluru Rural', recommended_amount_lakh: 14.0, sanctioned_amount_lakh: 13.5, total_expenditure_lakh: 13.4, status: 'COMPLETED', recommended_date: '2023-07-10', sanctioned_date: '2023-09-01', first_expenditure_date: '2023-10-15', latest_expenditure_date: '2024-04-20', completion_date: '2024-04-25', calamity_id: null, vendor_ids: ['V001'] },
  // Uttar Pradesh – MP003
  { internal_work_key: 'IWK-UP-001', official_work_id: null, mp_id: 'MP003', ida_id: 'IDA-UP-01', category: 'Road Construction', description: 'Four-laning of internal road, Aliganj sector, Lucknow', state: 'Uttar Pradesh', district: 'Lucknow', recommended_amount_lakh: 150.0, sanctioned_amount_lakh: 148.0, total_expenditure_lakh: 146.5, status: 'COMPLETED', recommended_date: '2021-10-05', sanctioned_date: '2021-12-10', first_expenditure_date: '2022-02-01', latest_expenditure_date: '2023-08-15', completion_date: '2023-08-25', calamity_id: null, vendor_ids: ['V003'] },
  { internal_work_key: 'IWK-UP-002', official_work_id: null, mp_id: 'MP003', ida_id: 'IDA-UP-01', category: 'Community Hall', description: 'Construction of multi-purpose community hall at Kakori', state: 'Uttar Pradesh', district: 'Lucknow', recommended_amount_lakh: 85.0, sanctioned_amount_lakh: 83.0, total_expenditure_lakh: 106.2, status: 'ONGOING', recommended_date: '2022-05-10', sanctioned_date: '2022-08-01', first_expenditure_date: '2022-10-15', latest_expenditure_date: '2025-10-01', completion_date: null, calamity_id: null, vendor_ids: ['V003', 'V009'] },
  { internal_work_key: 'IWK-UP-003', official_work_id: null, mp_id: 'MP003', ida_id: 'IDA-UP-01', category: 'Drinking Water Supply', description: 'Installation of water purification plant at Mohanlalganj block', state: 'Uttar Pradesh', district: 'Lucknow', recommended_amount_lakh: 40.0, sanctioned_amount_lakh: 39.5, total_expenditure_lakh: 39.2, status: 'COMPLETED', recommended_date: '2023-03-15', sanctioned_date: '2023-05-20', first_expenditure_date: '2023-07-01', latest_expenditure_date: '2024-02-10', completion_date: '2024-02-15', calamity_id: null, vendor_ids: ['V003'] },
  { internal_work_key: 'IWK-UP-004', official_work_id: null, mp_id: 'MP003', ida_id: 'IDA-UP-01', category: 'Bridge', description: 'Construction of bridge over Sai river at Malihabad', state: 'Uttar Pradesh', district: 'Lucknow', recommended_amount_lakh: 200.0, sanctioned_amount_lakh: 198.0, total_expenditure_lakh: 189.0, status: 'ONGOING', recommended_date: '2023-09-01', sanctioned_date: '2023-12-15', first_expenditure_date: '2024-03-01', latest_expenditure_date: '2025-11-01', completion_date: null, calamity_id: null, vendor_ids: ['V003', 'V009'] },
  { internal_work_key: 'IWK-UP-005', official_work_id: null, mp_id: 'MP003', ida_id: 'IDA-UP-01', category: 'School Building', description: 'Renovation of Government Inter College building at Chinhat', state: 'Uttar Pradesh', district: 'Lucknow', recommended_amount_lakh: 35.0, sanctioned_amount_lakh: 34.0, total_expenditure_lakh: 33.8, status: 'COMPLETED', recommended_date: '2022-12-01', sanctioned_date: '2023-02-10', first_expenditure_date: '2023-04-01', latest_expenditure_date: '2023-10-20', completion_date: '2023-10-28', calamity_id: null, vendor_ids: ['V009'] },
  // UP – MP004
  { internal_work_key: 'IWK-UP-006', official_work_id: null, mp_id: 'MP004', ida_id: 'IDA-UP-02', category: 'Road Construction', description: 'Construction of rural road connecting Mainpuri-Shikohabad via Bhongaon', state: 'Uttar Pradesh', district: 'Mainpuri', recommended_amount_lakh: 90.0, sanctioned_amount_lakh: 88.5, total_expenditure_lakh: 88.0, status: 'COMPLETED', recommended_date: '2022-08-20', sanctioned_date: '2022-10-15', first_expenditure_date: '2022-12-01', latest_expenditure_date: '2023-09-10', completion_date: '2023-09-18', calamity_id: null, vendor_ids: ['V009'] },
  { internal_work_key: 'IWK-UP-007', official_work_id: null, mp_id: 'MP004', ida_id: 'IDA-UP-02', category: 'Drinking Water Supply', description: 'Piped water supply scheme for Kishni block villages', state: 'Uttar Pradesh', district: 'Mainpuri', recommended_amount_lakh: 55.0, sanctioned_amount_lakh: 54.0, total_expenditure_lakh: 42.5, status: 'ONGOING', recommended_date: '2024-01-10', sanctioned_date: '2024-03-20', first_expenditure_date: '2024-06-01', latest_expenditure_date: '2025-09-01', completion_date: null, calamity_id: null, vendor_ids: ['V009'] },
  { internal_work_key: 'IWK-UP-008', official_work_id: null, mp_id: 'MP004', ida_id: 'IDA-UP-02', category: 'Community Hall', description: 'Construction of panchayat bhawan at Kuraoli', state: 'Uttar Pradesh', district: 'Mainpuri', recommended_amount_lakh: 25.0, sanctioned_amount_lakh: 24.5, total_expenditure_lakh: 24.0, status: 'COMPLETED', recommended_date: '2023-05-01', sanctioned_date: '2023-07-10', first_expenditure_date: '2023-09-01', latest_expenditure_date: '2024-03-20', completion_date: '2024-03-28', calamity_id: null, vendor_ids: ['V003'] },
  { internal_work_key: 'IWK-UP-009', official_work_id: null, mp_id: 'MP004', ida_id: 'IDA-UP-02', category: 'Road Construction', description: 'Concrete road in Barnahal ward, Mainpuri town', state: 'Uttar Pradesh', district: 'Mainpuri', recommended_amount_lakh: 38.0, sanctioned_amount_lakh: 37.0, total_expenditure_lakh: 36.8, status: 'COMPLETED', recommended_date: '2022-07-15', sanctioned_date: '2022-09-20', first_expenditure_date: '2022-11-01', latest_expenditure_date: '2023-06-10', completion_date: '2023-06-18', calamity_id: null, vendor_ids: ['V009'] },
  // Maharashtra – MP005
  { internal_work_key: 'IWK-MH-001', official_work_id: null, mp_id: 'MP005', ida_id: 'IDA-MH-01', category: 'Road Construction', description: 'Black-topping of Baramati-Phaltan state highway stretch', state: 'Maharashtra', district: 'Pune', recommended_amount_lakh: 110.0, sanctioned_amount_lakh: 108.0, total_expenditure_lakh: 107.5, status: 'COMPLETED', recommended_date: '2022-03-05', sanctioned_date: '2022-05-20', first_expenditure_date: '2022-07-10', latest_expenditure_date: '2023-04-15', completion_date: '2023-04-20', calamity_id: null, vendor_ids: ['V004'] },
  { internal_work_key: 'IWK-MH-002', official_work_id: null, mp_id: 'MP005', ida_id: 'IDA-MH-01', category: 'Irrigation', description: 'Construction of check dam on Neera river at Indapur', state: 'Maharashtra', district: 'Pune', recommended_amount_lakh: 180.0, sanctioned_amount_lakh: 176.0, total_expenditure_lakh: 175.5, status: 'COMPLETED', recommended_date: '2021-08-10', sanctioned_date: '2021-11-01', first_expenditure_date: '2022-01-15', latest_expenditure_date: '2023-10-20', completion_date: '2023-11-01', calamity_id: null, vendor_ids: ['V004', 'V011'] },
  { internal_work_key: 'IWK-MH-003', official_work_id: null, mp_id: 'MP005', ida_id: 'IDA-MH-01', category: 'Community Hall', description: 'Construction of community centre at Jejuri', state: 'Maharashtra', district: 'Pune', recommended_amount_lakh: 62.0, sanctioned_amount_lakh: 60.5, total_expenditure_lakh: 77.3, status: 'COMPLETED', recommended_date: '2022-01-20', sanctioned_date: '2022-04-05', first_expenditure_date: '2022-06-01', latest_expenditure_date: '2024-05-15', completion_date: '2024-05-20', calamity_id: null, vendor_ids: ['V011', 'V004'] },
  { internal_work_key: 'IWK-MH-004', official_work_id: null, mp_id: 'MP005', ida_id: 'IDA-MH-01', category: 'Drinking Water Supply', description: 'Overhead water storage tank at Daund taluka', state: 'Maharashtra', district: 'Pune', recommended_amount_lakh: 32.0, sanctioned_amount_lakh: 31.5, total_expenditure_lakh: 31.0, status: 'COMPLETED', recommended_date: '2023-06-10', sanctioned_date: '2023-08-01', first_expenditure_date: '2023-09-15', latest_expenditure_date: '2024-03-10', completion_date: '2024-03-18', calamity_id: null, vendor_ids: ['V004'] },
  { internal_work_key: 'IWK-MH-005', official_work_id: null, mp_id: 'MP005', ida_id: 'IDA-MH-01', category: 'School Building', description: 'Construction of science laboratory block at Zilla Parishad High School, Baramati', state: 'Maharashtra', district: 'Pune', recommended_amount_lakh: 45.0, sanctioned_amount_lakh: 44.0, total_expenditure_lakh: 28.5, status: 'ONGOING', recommended_date: '2025-01-15', sanctioned_date: '2025-03-10', first_expenditure_date: '2025-05-01', latest_expenditure_date: '2025-09-20', completion_date: null, calamity_id: null, vendor_ids: ['V011'] },
  // Maharashtra – MP006
  { internal_work_key: 'IWK-MH-006', official_work_id: null, mp_id: 'MP006', ida_id: 'IDA-MH-02', category: 'Road Construction', description: 'Reconstruction of internal roads at Kalyan East industrial area', state: 'Maharashtra', district: 'Thane', recommended_amount_lakh: 95.0, sanctioned_amount_lakh: 93.5, total_expenditure_lakh: 93.0, status: 'COMPLETED', recommended_date: '2022-02-10', sanctioned_date: '2022-04-15', first_expenditure_date: '2022-06-01', latest_expenditure_date: '2023-03-25', completion_date: '2023-04-01', calamity_id: null, vendor_ids: ['V004'] },
  { internal_work_key: 'IWK-MH-007', official_work_id: null, mp_id: 'MP006', ida_id: 'IDA-MH-02', category: 'Drainage', description: 'Underground drainage system for Dombivli area', state: 'Maharashtra', district: 'Thane', recommended_amount_lakh: 130.0, sanctioned_amount_lakh: 128.0, total_expenditure_lakh: 163.8, status: 'ONGOING', recommended_date: '2022-07-05', sanctioned_date: '2022-10-01', first_expenditure_date: '2023-01-15', latest_expenditure_date: '2025-10-20', completion_date: null, calamity_id: null, vendor_ids: ['V004', 'V011'] },
  { internal_work_key: 'IWK-MH-008', official_work_id: null, mp_id: 'MP006', ida_id: 'IDA-MH-02', category: 'Bridge', description: 'Construction of ROB (Road Over Bridge) at Kalyan railway crossing', state: 'Maharashtra', district: 'Thane', recommended_amount_lakh: 250.0, sanctioned_amount_lakh: 245.0, total_expenditure_lakh: 198.0, status: 'ONGOING', recommended_date: '2023-05-20', sanctioned_date: '2023-09-10', first_expenditure_date: '2024-01-01', latest_expenditure_date: '2025-11-15', completion_date: null, calamity_id: null, vendor_ids: ['V004'] },
  { internal_work_key: 'IWK-MH-009', official_work_id: null, mp_id: 'MP006', ida_id: 'IDA-MH-02', category: 'Community Hall', description: 'Construction of cultural hall at Ambernath', state: 'Maharashtra', district: 'Thane', recommended_amount_lakh: 70.0, sanctioned_amount_lakh: 68.5, total_expenditure_lakh: 68.0, status: 'COMPLETED', recommended_date: '2022-09-10', sanctioned_date: '2022-11-15', first_expenditure_date: '2023-01-01', latest_expenditure_date: '2024-01-20', completion_date: '2024-01-28', calamity_id: null, vendor_ids: ['V011'] },
  // Tamil Nadu – MP007
  { internal_work_key: 'IWK-TN-001', official_work_id: null, mp_id: 'MP007', ida_id: 'IDA-TN-01', category: 'Fishing Harbour', description: 'Development of minor fishing harbour at Kayalpattinam', state: 'Tamil Nadu', district: 'Thoothukudi', recommended_amount_lakh: 200.0, sanctioned_amount_lakh: 196.0, total_expenditure_lakh: 193.5, status: 'COMPLETED', recommended_date: '2021-07-15', sanctioned_date: '2021-10-20', first_expenditure_date: '2022-01-01', latest_expenditure_date: '2023-12-15', completion_date: '2023-12-22', calamity_id: null, vendor_ids: ['V005', 'V012'] },
  { internal_work_key: 'IWK-TN-002', official_work_id: null, mp_id: 'MP007', ida_id: 'IDA-TN-01', category: 'Road Construction', description: 'Four-lane road development at Thoothukudi port connectivity corridor', state: 'Tamil Nadu', district: 'Thoothukudi', recommended_amount_lakh: 160.0, sanctioned_amount_lakh: 157.0, total_expenditure_lakh: 155.8, status: 'COMPLETED', recommended_date: '2022-01-10', sanctioned_date: '2022-03-20', first_expenditure_date: '2022-05-15', latest_expenditure_date: '2023-07-10', completion_date: '2023-07-18', calamity_id: null, vendor_ids: ['V012'] },
  { internal_work_key: 'IWK-TN-003', official_work_id: null, mp_id: 'MP007', ida_id: 'IDA-TN-01', category: 'Cyclone Relief Infrastructure', description: 'Repair and restoration of coastal roads after Cyclone Michaung', state: 'Tamil Nadu', district: 'Thoothukudi', recommended_amount_lakh: 75.0, sanctioned_amount_lakh: 73.5, total_expenditure_lakh: 95.7, status: 'COMPLETED', recommended_date: '2024-01-05', sanctioned_date: '2024-01-20', first_expenditure_date: '2024-02-01', latest_expenditure_date: '2024-08-10', completion_date: '2024-08-18', calamity_id: 'CAL002', vendor_ids: ['V005', 'V012'] },
  { internal_work_key: 'IWK-TN-004', official_work_id: null, mp_id: 'MP007', ida_id: 'IDA-TN-01', category: 'Community Hall', description: 'Construction of fishermen community hall at Colachel', state: 'Tamil Nadu', district: 'Thoothukudi', recommended_amount_lakh: 42.0, sanctioned_amount_lakh: 41.0, total_expenditure_lakh: 40.5, status: 'COMPLETED', recommended_date: '2023-04-15', sanctioned_date: '2023-06-20', first_expenditure_date: '2023-08-01', latest_expenditure_date: '2024-03-15', completion_date: '2024-03-22', calamity_id: null, vendor_ids: ['V012'] },
  { internal_work_key: 'IWK-TN-005', official_work_id: null, mp_id: 'MP007', ida_id: 'IDA-TN-01', category: 'School Building', description: 'Construction of new block at Government Girls Higher Secondary School, Thoothukudi', state: 'Tamil Nadu', district: 'Thoothukudi', recommended_amount_lakh: 48.0, sanctioned_amount_lakh: 47.0, total_expenditure_lakh: 36.2, status: 'ONGOING', recommended_date: '2024-09-10', sanctioned_date: '2024-11-01', first_expenditure_date: '2025-01-15', latest_expenditure_date: '2025-10-01', completion_date: null, calamity_id: null, vendor_ids: ['V005'] },
  // Tamil Nadu – MP008
  { internal_work_key: 'IWK-TN-006', official_work_id: null, mp_id: 'MP008', ida_id: 'IDA-TN-02', category: 'Road Construction', description: 'Improvement of hill road from Ooty to Kotagiri', state: 'Tamil Nadu', district: 'The Nilgiris', recommended_amount_lakh: 120.0, sanctioned_amount_lakh: 118.0, total_expenditure_lakh: 117.5, status: 'COMPLETED', recommended_date: '2022-05-10', sanctioned_date: '2022-07-20', first_expenditure_date: '2022-09-15', latest_expenditure_date: '2023-08-30', completion_date: '2023-09-05', calamity_id: null, vendor_ids: ['V012'] },
  { internal_work_key: 'IWK-TN-007', official_work_id: null, mp_id: 'MP008', ida_id: 'IDA-TN-02', category: 'Bridge', description: 'Construction of pedestrian bridge at Gudalur market area', state: 'Tamil Nadu', district: 'The Nilgiris', recommended_amount_lakh: 55.0, sanctioned_amount_lakh: 54.0, total_expenditure_lakh: 53.5, status: 'COMPLETED', recommended_date: '2023-02-20', sanctioned_date: '2023-04-15', first_expenditure_date: '2023-06-01', latest_expenditure_date: '2024-01-25', completion_date: '2024-02-01', calamity_id: null, vendor_ids: ['V005'] },
  { internal_work_key: 'IWK-TN-008', official_work_id: null, mp_id: 'MP008', ida_id: 'IDA-TN-02', category: 'Drinking Water Supply', description: 'Protected water supply scheme for tribal hamlets in Nilgiris', state: 'Tamil Nadu', district: 'The Nilgiris', recommended_amount_lakh: 65.0, sanctioned_amount_lakh: 63.5, total_expenditure_lakh: 48.0, status: 'ONGOING', recommended_date: '2024-03-10', sanctioned_date: '2024-05-20', first_expenditure_date: '2024-07-01', latest_expenditure_date: '2025-09-15', completion_date: null, calamity_id: null, vendor_ids: ['V012'] },
  { internal_work_key: 'IWK-TN-009', official_work_id: null, mp_id: 'MP008', ida_id: 'IDA-TN-02', category: 'Community Hall', description: 'Renovation of estate workers community hall at Coonoor', state: 'Tamil Nadu', district: 'The Nilgiris', recommended_amount_lakh: 28.0, sanctioned_amount_lakh: 27.5, total_expenditure_lakh: 27.3, status: 'COMPLETED', recommended_date: '2023-08-05', sanctioned_date: '2023-10-01', first_expenditure_date: '2023-11-15', latest_expenditure_date: '2024-06-10', completion_date: '2024-06-18', calamity_id: null, vendor_ids: ['V005'] },
  // West Bengal
  { internal_work_key: 'IWK-WB-001', official_work_id: null, mp_id: 'MP010', ida_id: 'IDA-WB-01', category: 'Road Construction', description: 'Improvement of road from Krishnanagar to Nabadwip', state: 'West Bengal', district: 'Nadia', recommended_amount_lakh: 88.0, sanctioned_amount_lakh: 86.0, total_expenditure_lakh: 85.5, status: 'COMPLETED', recommended_date: '2022-04-10', sanctioned_date: '2022-06-20', first_expenditure_date: '2022-08-15', latest_expenditure_date: '2023-05-30', completion_date: '2023-06-05', calamity_id: null, vendor_ids: ['V010'] },
  { internal_work_key: 'IWK-WB-002', official_work_id: null, mp_id: 'MP010', ida_id: 'IDA-WB-01', category: 'Flood Relief Infrastructure', description: 'Embankment reinforcement along Jalangi river (flood calamity work)', state: 'West Bengal', district: 'Nadia', recommended_amount_lakh: 95.0, sanctioned_amount_lakh: 93.0, total_expenditure_lakh: 118.5, status: 'COMPLETED', recommended_date: '2024-08-01', sanctioned_date: '2024-08-20', first_expenditure_date: '2024-09-01', latest_expenditure_date: '2025-03-15', completion_date: '2025-03-20', calamity_id: 'CAL003', vendor_ids: ['V010'] },
  { internal_work_key: 'IWK-WB-003', official_work_id: null, mp_id: 'MP010', ida_id: 'IDA-WB-01', category: 'School Building', description: 'Construction of primary school building at Karimpur', state: 'West Bengal', district: 'Nadia', recommended_amount_lakh: 38.0, sanctioned_amount_lakh: 37.0, total_expenditure_lakh: 36.8, status: 'COMPLETED', recommended_date: '2023-01-10', sanctioned_date: '2023-03-05', first_expenditure_date: '2023-05-01', latest_expenditure_date: '2023-12-20', completion_date: '2023-12-28', calamity_id: null, vendor_ids: ['V010'] },
  { internal_work_key: 'IWK-WB-004', official_work_id: null, mp_id: 'MP010', ida_id: 'IDA-WB-01', category: 'Community Hall', description: 'Construction of library and reading room at Ranaghat', state: 'West Bengal', district: 'Nadia', recommended_amount_lakh: 30.0, sanctioned_amount_lakh: 29.0, total_expenditure_lakh: 28.5, status: 'COMPLETED', recommended_date: '2022-10-15', sanctioned_date: '2022-12-20', first_expenditure_date: '2023-02-01', latest_expenditure_date: '2023-09-15', completion_date: '2023-09-22', calamity_id: null, vendor_ids: ['V010'] },
  { internal_work_key: 'IWK-WB-005', official_work_id: null, mp_id: 'MP009', ida_id: 'IDA-WB-01', category: 'Drinking Water Supply', description: 'Water supply augmentation project for Berhampore area', state: 'West Bengal', district: 'Nadia', recommended_amount_lakh: 72.0, sanctioned_amount_lakh: 70.0, total_expenditure_lakh: 53.0, status: 'ONGOING', recommended_date: '2024-05-10', sanctioned_date: '2024-07-15', first_expenditure_date: '2024-09-01', latest_expenditure_date: '2025-10-01', completion_date: null, calamity_id: null, vendor_ids: ['V010'] },
  // Kerala
  { internal_work_key: 'IWK-KL-001', official_work_id: null, mp_id: 'MP011', ida_id: 'IDA-KL-01', category: 'Road Construction', description: 'Reconstruction of road at Palayam junction, Thiruvananthapuram', state: 'Kerala', district: 'Thiruvananthapuram', recommended_amount_lakh: 65.0, sanctioned_amount_lakh: 63.5, total_expenditure_lakh: 63.0, status: 'COMPLETED', recommended_date: '2022-06-15', sanctioned_date: '2022-08-20', first_expenditure_date: '2022-10-01', latest_expenditure_date: '2023-06-15', completion_date: '2023-06-22', calamity_id: null, vendor_ids: ['V006'] },
  { internal_work_key: 'IWK-KL-002', official_work_id: null, mp_id: 'MP011', ida_id: 'IDA-KL-01', category: 'Drinking Water Supply', description: 'Piped water supply scheme for Vattiyoorkavu ward', state: 'Kerala', district: 'Thiruvananthapuram', recommended_amount_lakh: 35.0, sanctioned_amount_lakh: 34.0, total_expenditure_lakh: 33.8, status: 'COMPLETED', recommended_date: '2023-03-10', sanctioned_date: '2023-05-15', first_expenditure_date: '2023-07-01', latest_expenditure_date: '2024-02-25', completion_date: '2024-03-01', calamity_id: null, vendor_ids: ['V006'] },
  { internal_work_key: 'IWK-KL-003', official_work_id: null, mp_id: 'MP011', ida_id: 'IDA-KL-01', category: 'Community Hall', description: 'Renovation of cultural centre at East Fort, Thiruvananthapuram', state: 'Kerala', district: 'Thiruvananthapuram', recommended_amount_lakh: 50.0, sanctioned_amount_lakh: 48.5, total_expenditure_lakh: 61.8, status: 'COMPLETED', recommended_date: '2022-02-20', sanctioned_date: '2022-04-10', first_expenditure_date: '2022-06-01', latest_expenditure_date: '2024-03-20', completion_date: '2024-04-01', calamity_id: null, vendor_ids: ['V006'] },
  { internal_work_key: 'IWK-KL-004', official_work_id: null, mp_id: 'MP011', ida_id: 'IDA-KL-01', category: 'School Building', description: 'Construction of smart classrooms at Government School, Pettah', state: 'Kerala', district: 'Thiruvananthapuram', recommended_amount_lakh: 28.0, sanctioned_amount_lakh: 27.5, total_expenditure_lakh: 27.2, status: 'COMPLETED', recommended_date: '2023-09-10', sanctioned_date: '2023-11-05', first_expenditure_date: '2024-01-10', latest_expenditure_date: '2024-07-20', completion_date: '2024-07-28', calamity_id: null, vendor_ids: ['V006'] },
  { internal_work_key: 'IWK-KL-005', official_work_id: null, mp_id: 'MP012', ida_id: 'IDA-KL-01', category: 'Sanitation', description: 'Construction of public toilets at Chalai market complex', state: 'Kerala', district: 'Thiruvananthapuram', recommended_amount_lakh: 16.0, sanctioned_amount_lakh: 15.5, total_expenditure_lakh: 15.3, status: 'COMPLETED', recommended_date: '2022-11-01', sanctioned_date: '2022-12-20', first_expenditure_date: '2023-02-01', latest_expenditure_date: '2023-08-10', completion_date: '2023-08-18', calamity_id: null, vendor_ids: ['V006'] },
  { internal_work_key: 'IWK-KL-006', official_work_id: null, mp_id: 'MP012', ida_id: 'IDA-KL-01', category: 'Road Construction', description: 'Widening of road at Nemom constituency link road', state: 'Kerala', district: 'Thiruvananthapuram', recommended_amount_lakh: 78.0, sanctioned_amount_lakh: 76.0, total_expenditure_lakh: 57.5, status: 'ONGOING', recommended_date: '2024-04-10', sanctioned_date: '2024-06-20', first_expenditure_date: '2024-08-01', latest_expenditure_date: '2025-10-15', completion_date: null, calamity_id: null, vendor_ids: ['V006'] },
  // Rajasthan
  { internal_work_key: 'IWK-RJ-001', official_work_id: null, mp_id: 'MP013', ida_id: 'IDA-RJ-01', category: 'Drinking Water Supply', description: 'Underground pipeline for potable water supply in drought-affected Sikar district', state: 'Rajasthan', district: 'Jaipur', recommended_amount_lakh: 110.0, sanctioned_amount_lakh: 108.0, total_expenditure_lakh: 107.5, status: 'COMPLETED', recommended_date: '2023-05-10', sanctioned_date: '2023-07-20', first_expenditure_date: '2023-09-01', latest_expenditure_date: '2024-07-15', completion_date: '2024-07-22', calamity_id: 'CAL004', vendor_ids: ['V007'] },
  { internal_work_key: 'IWK-RJ-002', official_work_id: null, mp_id: 'MP013', ida_id: 'IDA-RJ-01', category: 'Road Construction', description: 'Strengthening of Amber-Jaipur heritage road corridor', state: 'Rajasthan', district: 'Jaipur', recommended_amount_lakh: 85.0, sanctioned_amount_lakh: 83.5, total_expenditure_lakh: 82.8, status: 'COMPLETED', recommended_date: '2022-08-15', sanctioned_date: '2022-10-20', first_expenditure_date: '2022-12-01', latest_expenditure_date: '2023-09-20', completion_date: '2023-09-28', calamity_id: null, vendor_ids: ['V007'] },
  { internal_work_key: 'IWK-RJ-003', official_work_id: null, mp_id: 'MP013', ida_id: 'IDA-RJ-01', category: 'Community Hall', description: 'Construction of gram sabha bhawan at Amer block', state: 'Rajasthan', district: 'Jaipur', recommended_amount_lakh: 35.0, sanctioned_amount_lakh: 34.0, total_expenditure_lakh: 33.5, status: 'COMPLETED', recommended_date: '2023-10-05', sanctioned_date: '2023-12-10', first_expenditure_date: '2024-02-01', latest_expenditure_date: '2024-09-15', completion_date: '2024-09-22', calamity_id: null, vendor_ids: ['V007'] },
  { internal_work_key: 'IWK-RJ-004', official_work_id: null, mp_id: 'MP014', ida_id: 'IDA-RJ-02', category: 'Road Construction', description: 'Rural road improvement connecting Tonk-Uniara', state: 'Rajasthan', district: 'Tonk', recommended_amount_lakh: 72.0, sanctioned_amount_lakh: 70.5, total_expenditure_lakh: 70.0, status: 'COMPLETED', recommended_date: '2022-06-20', sanctioned_date: '2022-08-25', first_expenditure_date: '2022-10-15', latest_expenditure_date: '2023-06-25', completion_date: '2023-07-01', calamity_id: null, vendor_ids: ['V007'] },
  { internal_work_key: 'IWK-RJ-005', official_work_id: null, mp_id: 'MP014', ida_id: 'IDA-RJ-02', category: 'Drinking Water Supply', description: 'Deepening and renovation of village ponds in drought areas Tonk', state: 'Rajasthan', district: 'Tonk', recommended_amount_lakh: 48.0, sanctioned_amount_lakh: 47.0, total_expenditure_lakh: 35.8, status: 'ONGOING', recommended_date: '2024-06-10', sanctioned_date: '2024-08-20', first_expenditure_date: '2024-10-01', latest_expenditure_date: '2025-09-10', completion_date: null, calamity_id: 'CAL004', vendor_ids: ['V007'] },
  { internal_work_key: 'IWK-RJ-006', official_work_id: null, mp_id: 'MP014', ida_id: 'IDA-RJ-02', category: 'School Building', description: 'Construction of new secondary school building at Malpura', state: 'Rajasthan', district: 'Tonk', recommended_amount_lakh: 55.0, sanctioned_amount_lakh: 53.5, total_expenditure_lakh: 40.2, status: 'ONGOING', recommended_date: '2024-09-01', sanctioned_date: '2024-11-15', first_expenditure_date: '2025-01-10', latest_expenditure_date: '2025-10-01', completion_date: null, calamity_id: null, vendor_ids: ['V007'] },
  // UP – MP015
  { internal_work_key: 'IWK-UP-010', official_work_id: null, mp_id: 'MP015', ida_id: 'IDA-UP-01', category: 'Road Construction', description: 'Construction of link road from Amethi to Salon via Musafirkhana', state: 'Uttar Pradesh', district: 'Lucknow', recommended_amount_lakh: 140.0, sanctioned_amount_lakh: 138.0, total_expenditure_lakh: 137.0, status: 'COMPLETED', recommended_date: '2022-01-15', sanctioned_date: '2022-03-20', first_expenditure_date: '2022-05-10', latest_expenditure_date: '2023-04-20', completion_date: '2023-04-28', calamity_id: null, vendor_ids: ['V003'] },
  { internal_work_key: 'IWK-UP-011', official_work_id: null, mp_id: 'MP015', ida_id: 'IDA-UP-01', category: 'Community Hall', description: 'Construction of Jan Suvidha Kendra at Gauriganj block', state: 'Uttar Pradesh', district: 'Lucknow', recommended_amount_lakh: 45.0, sanctioned_amount_lakh: 44.0, total_expenditure_lakh: 43.5, status: 'COMPLETED', recommended_date: '2023-04-10', sanctioned_date: '2023-06-15', first_expenditure_date: '2023-08-01', latest_expenditure_date: '2024-04-20', completion_date: '2024-04-28', calamity_id: null, vendor_ids: ['V009'] },
  { internal_work_key: 'IWK-UP-012', official_work_id: null, mp_id: 'MP015', ida_id: 'IDA-UP-01', category: 'School Building', description: 'Construction of vocational training centre at Sultanpur', state: 'Uttar Pradesh', district: 'Lucknow', recommended_amount_lakh: 68.0, sanctioned_amount_lakh: 66.5, total_expenditure_lakh: 84.3, status: 'ONGOING', recommended_date: '2022-10-20', sanctioned_date: '2022-12-15', first_expenditure_date: '2023-02-01', latest_expenditure_date: '2025-10-01', completion_date: null, calamity_id: null, vendor_ids: ['V003', 'V009'] },
  { internal_work_key: 'IWK-UP-013', official_work_id: null, mp_id: 'MP015', ida_id: 'IDA-UP-01', category: 'Bridge', description: 'Construction of bridge over Sharda canal at Jagdishpur', state: 'Uttar Pradesh', district: 'Lucknow', recommended_amount_lakh: 175.0, sanctioned_amount_lakh: 172.0, total_expenditure_lakh: 137.5, status: 'ONGOING', recommended_date: '2024-02-10', sanctioned_date: '2024-05-01', first_expenditure_date: '2024-07-15', latest_expenditure_date: '2025-11-01', completion_date: null, calamity_id: null, vendor_ids: ['V003'] },
  // Additional works
  { internal_work_key: 'IWK-KA-016', official_work_id: null, mp_id: 'MP001', ida_id: 'IDA-KA-01', category: 'Irrigation', description: 'Renovation of minor irrigation tank at Annigeri village', state: 'Karnataka', district: 'Dharwad', recommended_amount_lakh: 52.0, sanctioned_amount_lakh: 50.5, total_expenditure_lakh: 50.2, status: 'COMPLETED', recommended_date: '2023-06-05', sanctioned_date: '2023-08-15', first_expenditure_date: '2023-10-01', latest_expenditure_date: '2024-06-15', completion_date: '2024-06-22', calamity_id: null, vendor_ids: ['V001'] },
  { internal_work_key: 'IWK-KA-017', official_work_id: null, mp_id: 'MP002', ida_id: 'IDA-KA-02', category: 'Road Construction', description: 'Improvement of internal roads in Ramanagara town', state: 'Karnataka', district: 'Bengaluru Rural', recommended_amount_lakh: 62.0, sanctioned_amount_lakh: 60.5, total_expenditure_lakh: 59.8, status: 'COMPLETED', recommended_date: '2022-09-15', sanctioned_date: '2022-11-20', first_expenditure_date: '2023-01-10', latest_expenditure_date: '2023-10-20', completion_date: '2023-10-28', calamity_id: null, vendor_ids: ['V002'] },
  { internal_work_key: 'IWK-KA-018', official_work_id: null, mp_id: 'MP001', ida_id: 'IDA-KA-01', category: 'Anganwadi', description: 'Construction of Anganwadi centres at Kalghatagi Batch 3 units', state: 'Karnataka', district: 'Dharwad', recommended_amount_lakh: 21.0, sanctioned_amount_lakh: 20.5, total_expenditure_lakh: 20.3, status: 'COMPLETED', recommended_date: '2024-01-10', sanctioned_date: '2024-03-05', first_expenditure_date: '2024-05-01', latest_expenditure_date: '2024-11-20', completion_date: '2024-11-28', calamity_id: null, vendor_ids: ['V001'] },
  { internal_work_key: 'IWK-KA-019', official_work_id: null, mp_id: 'MP002', ida_id: 'IDA-KA-02', category: 'Community Hall', description: 'Construction of indoor sports stadium at Magadi', state: 'Karnataka', district: 'Bengaluru Rural', recommended_amount_lakh: 95.0, sanctioned_amount_lakh: 93.0, total_expenditure_lakh: 117.6, status: 'ONGOING', recommended_date: '2022-03-15', sanctioned_date: '2022-06-01', first_expenditure_date: '2022-08-15', latest_expenditure_date: '2025-10-15', completion_date: null, calamity_id: null, vendor_ids: ['V008', 'V002'] },
  { internal_work_key: 'IWK-KA-020', official_work_id: null, mp_id: 'MP001', ida_id: 'IDA-KA-01', category: 'Drinking Water Supply', description: 'Pipeline extension for drinking water to Hubli outskirts', state: 'Karnataka', district: 'Dharwad', recommended_amount_lakh: 33.0, sanctioned_amount_lakh: 32.0, total_expenditure_lakh: 24.8, status: 'ONGOING', recommended_date: '2025-03-10', sanctioned_date: '2025-05-20', first_expenditure_date: '2025-07-01', latest_expenditure_date: '2025-09-15', completion_date: null, calamity_id: null, vendor_ids: ['V001'] },
  { internal_work_key: 'IWK-UP-014', official_work_id: null, mp_id: 'MP003', ida_id: 'IDA-UP-01', category: 'Drainage', description: 'Storm water drain construction at Sushant Golf City area, Lucknow', state: 'Uttar Pradesh', district: 'Lucknow', recommended_amount_lakh: 65.0, sanctioned_amount_lakh: 63.5, total_expenditure_lakh: 63.0, status: 'COMPLETED', recommended_date: '2023-07-10', sanctioned_date: '2023-09-20', first_expenditure_date: '2023-11-01', latest_expenditure_date: '2024-07-10', completion_date: '2024-07-18', calamity_id: null, vendor_ids: ['V003'] },
  { internal_work_key: 'IWK-UP-015', official_work_id: null, mp_id: 'MP004', ida_id: 'IDA-UP-02', category: 'School Building', description: 'Construction of computer lab at Government Inter College, Mainpuri', state: 'Uttar Pradesh', district: 'Mainpuri', recommended_amount_lakh: 22.0, sanctioned_amount_lakh: 21.5, total_expenditure_lakh: 21.0, status: 'COMPLETED', recommended_date: '2023-11-01', sanctioned_date: '2024-01-10', first_expenditure_date: '2024-03-01', latest_expenditure_date: '2024-09-20', completion_date: '2024-09-28', calamity_id: null, vendor_ids: ['V009'] },
  { internal_work_key: 'IWK-UP-016', official_work_id: null, mp_id: 'MP003', ida_id: 'IDA-UP-01', category: 'Anganwadi', description: 'Construction of Anganwadi centres Batch 5 units in Gosainganj block', state: 'Uttar Pradesh', district: 'Lucknow', recommended_amount_lakh: 35.0, sanctioned_amount_lakh: 34.0, total_expenditure_lakh: 33.5, status: 'COMPLETED', recommended_date: '2023-08-15', sanctioned_date: '2023-10-20', first_expenditure_date: '2023-12-01', latest_expenditure_date: '2024-06-25', completion_date: '2024-07-01', calamity_id: null, vendor_ids: ['V003'] },
  { internal_work_key: 'IWK-KA-021', official_work_id: null, mp_id: 'MP001', ida_id: 'IDA-KA-01', category: 'Community Hall', description: 'Construction of gram panchayat community hall at Dharwad taluka', state: 'Karnataka', district: 'Dharwad', recommended_amount_lakh: 44.0, sanctioned_amount_lakh: 42.5, total_expenditure_lakh: 42.0, status: 'COMPLETED', recommended_date: '2023-03-10', sanctioned_date: '2023-05-15', first_expenditure_date: '2023-07-01', latest_expenditure_date: '2024-03-10', completion_date: '2024-03-18', calamity_id: null, vendor_ids: ['V008'] },
  { internal_work_key: 'IWK-KA-022', official_work_id: null, mp_id: 'MP001', ida_id: 'IDA-KA-01', category: 'Road Construction', description: 'Proposed CC road from Dharwad Railway Station to Medical College', state: 'Karnataka', district: 'Dharwad', recommended_amount_lakh: 28.0, sanctioned_amount_lakh: null, total_expenditure_lakh: 0, status: 'RECOMMENDED', recommended_date: '2025-08-20', sanctioned_date: null, first_expenditure_date: null, latest_expenditure_date: null, completion_date: null, calamity_id: null, vendor_ids: [] },
  { internal_work_key: 'IWK-MH-010', official_work_id: null, mp_id: 'MP005', ida_id: 'IDA-MH-01', category: 'Drinking Water Supply', description: 'Proposed water supply augmentation at Indapur block', state: 'Maharashtra', district: 'Pune', recommended_amount_lakh: 40.0, sanctioned_amount_lakh: null, total_expenditure_lakh: 0, status: 'RECOMMENDED', recommended_date: '2025-09-01', sanctioned_date: null, first_expenditure_date: null, latest_expenditure_date: null, completion_date: null, calamity_id: null, vendor_ids: [] },
  { internal_work_key: 'IWK-TN-010', official_work_id: null, mp_id: 'MP007', ida_id: 'IDA-TN-01', category: 'Bridge', description: 'Proposed construction of causeway at Kayalpattinam creek crossing', state: 'Tamil Nadu', district: 'Thoothukudi', recommended_amount_lakh: 85.0, sanctioned_amount_lakh: 83.0, total_expenditure_lakh: 0, status: 'SANCTIONED', recommended_date: '2025-04-10', sanctioned_date: '2025-07-20', first_expenditure_date: null, latest_expenditure_date: null, completion_date: null, calamity_id: null, vendor_ids: [] },
  { internal_work_key: 'IWK-RJ-007', official_work_id: null, mp_id: 'MP013', ida_id: 'IDA-RJ-01', category: 'Community Hall', description: 'Proposed gram panchayat bhawan at Sanganer block, Jaipur', state: 'Rajasthan', district: 'Jaipur', recommended_amount_lakh: 30.0, sanctioned_amount_lakh: 29.5, total_expenditure_lakh: 0, status: 'SANCTIONED', recommended_date: '2025-05-15', sanctioned_date: '2025-08-01', first_expenditure_date: null, latest_expenditure_date: null, completion_date: null, calamity_id: null, vendor_ids: [] },
  { internal_work_key: 'IWK-MH-011', official_work_id: null, mp_id: 'MP006', ida_id: 'IDA-MH-02', category: 'Anganwadi', description: 'Construction of Anganwadi centres at Ulhasnagar Batch 4 units', state: 'Maharashtra', district: 'Thane', recommended_amount_lakh: 28.0, sanctioned_amount_lakh: 27.5, total_expenditure_lakh: 27.2, status: 'COMPLETED', recommended_date: '2023-02-10', sanctioned_date: '2023-04-15', first_expenditure_date: '2023-06-01', latest_expenditure_date: '2024-01-10', completion_date: '2024-01-18', calamity_id: null, vendor_ids: ['V011'] },
  { internal_work_key: 'IWK-KL-007', official_work_id: null, mp_id: 'MP011', ida_id: 'IDA-KL-01', category: 'Irrigation', description: 'Renovation of minor irrigation channel at Nedumangad', state: 'Kerala', district: 'Thiruvananthapuram', recommended_amount_lakh: 42.0, sanctioned_amount_lakh: 41.0, total_expenditure_lakh: 40.5, status: 'COMPLETED', recommended_date: '2023-04-10', sanctioned_date: '2023-06-15', first_expenditure_date: '2023-08-01', latest_expenditure_date: '2024-04-10', completion_date: '2024-04-18', calamity_id: null, vendor_ids: ['V006'] },
  { internal_work_key: 'IWK-WB-006', official_work_id: null, mp_id: 'MP010', ida_id: 'IDA-WB-01', category: 'Road Construction', description: 'Construction of rural road at Tehatta block, Nadia district', state: 'West Bengal', district: 'Nadia', recommended_amount_lakh: 48.0, sanctioned_amount_lakh: 47.0, total_expenditure_lakh: 46.5, status: 'COMPLETED', recommended_date: '2023-05-10', sanctioned_date: '2023-07-15', first_expenditure_date: '2023-09-01', latest_expenditure_date: '2024-04-20', completion_date: '2024-04-28', calamity_id: null, vendor_ids: ['V010'] },
  { internal_work_key: 'IWK-TN-011', official_work_id: null, mp_id: 'MP008', ida_id: 'IDA-TN-02', category: 'School Building', description: 'Renovation of Government Tribal Residential School at Kotagiri', state: 'Tamil Nadu', district: 'The Nilgiris', recommended_amount_lakh: 42.0, sanctioned_amount_lakh: 41.0, total_expenditure_lakh: 40.8, status: 'COMPLETED', recommended_date: '2022-12-10', sanctioned_date: '2023-02-15', first_expenditure_date: '2023-04-01', latest_expenditure_date: '2023-11-20', completion_date: '2023-11-28', calamity_id: null, vendor_ids: ['V012'] },
  { internal_work_key: 'IWK-KA-023', official_work_id: null, mp_id: 'MP001', ida_id: 'IDA-KA-01', category: 'Drainage', description: 'Underground drainage network for Dharwad old city ward', state: 'Karnataka', district: 'Dharwad', recommended_amount_lakh: 78.0, sanctioned_amount_lakh: 76.0, total_expenditure_lakh: 98.4, status: 'COMPLETED', recommended_date: '2021-06-10', sanctioned_date: '2021-09-01', first_expenditure_date: '2021-11-15', latest_expenditure_date: '2024-08-10', completion_date: '2024-08-20', calamity_id: null, vendor_ids: ['V008', 'V001'] },
  { internal_work_key: 'IWK-UP-017', official_work_id: null, mp_id: 'MP003', ida_id: 'IDA-UP-01', category: 'Drainage', description: 'Construction of naala drainage channel in Gomti Nagar extension', state: 'Uttar Pradesh', district: 'Lucknow', recommended_amount_lakh: 42.0, sanctioned_amount_lakh: 41.0, total_expenditure_lakh: 40.8, status: 'COMPLETED', recommended_date: '2024-02-10', sanctioned_date: '2024-04-20', first_expenditure_date: '2024-06-01', latest_expenditure_date: '2025-01-20', completion_date: '2025-01-28', calamity_id: null, vendor_ids: ['V003'] },
];

function generateExpenditures() {
  const records = [];
  const highRiskKeys = ['IWK-KA-003','IWK-UP-002','IWK-MH-003','IWK-MH-007','IWK-KA-014','IWK-WB-002','IWK-TN-003','IWK-KL-003','IWK-KA-019','IWK-UP-012','IWK-KA-023'];
  worksRaw.forEach(w => {
    if (!w.first_expenditure_date || w.total_expenditure_lakh <= 0) return;
    const total = w.total_expenditure_lakh;
    const isHighRisk = highRiskKeys.includes(w.internal_work_key);
    const numPayments = Math.min(6, Math.max(2, Math.floor(total / 20)));
    const startDate = new Date(w.first_expenditure_date);
    const endDate = w.latest_expenditure_date ? new Date(w.latest_expenditure_date) : new Date();
    let remaining = total;
    for (let i = 0; i < numPayments; i++) {
      const isLast = i === numPayments - 1;
      let amt;
      if (isLast) {
        amt = Math.round(remaining * 100) / 100;
      } else if (isHighRisk && i === numPayments - 2) {
        amt = Math.round(total * 0.55 * 100) / 100;
      } else {
        const portion = remaining / (numPayments - i);
        amt = Math.round(portion * (0.5 + Math.random() * 0.5) * 100) / 100;
      }
      amt = Math.max(0.5, Math.min(amt, remaining));
      const fraction = i / Math.max(numPayments - 1, 1);
      const payDate = new Date(startDate.getTime() + fraction * (endDate.getTime() - startDate.getTime()));
      records.push({
        id: `EXP-${w.internal_work_key}-${i + 1}`,
        work_key: w.internal_work_key,
        date: payDate.toISOString().split('T')[0],
        vendor_id: w.vendor_ids[i % Math.max(w.vendor_ids.length, 1)] || 'V001',
        amount_lakh: amt,
        reference: `REF-${w.internal_work_key.replace('IWK-', '')}-${String(i + 1).padStart(3, '0')}`,
        status: 'PROCESSED',
      });
      remaining -= amt;
      if (remaining <= 0.01) break;
    }
  });
  return records;
}

function generateRiskHistory(works) {
  const history = {};
  works.forEach(w => {
    if (!w.sanctioned_date && !w.recommended_date) return;
    const entries = [];
    const baseDate = new Date(w.sanctioned_date || w.recommended_date);
    entries.push({ date: (w.sanctioned_date || w.recommended_date), level: 'LOW', note: 'Initial assessment after sanction' });
    if (['WATCH', 'HIGH', 'CRITICAL'].includes(w.risk_level)) {
      const d = new Date(baseDate); d.setMonth(d.getMonth() + 4);
      entries.push({ date: d.toISOString().split('T')[0], level: 'WATCH', note: 'Cost deviation signal appeared' });
    }
    if (['HIGH', 'CRITICAL'].includes(w.risk_level)) {
      const d = new Date(baseDate); d.setMonth(d.getMonth() + 8);
      entries.push({ date: d.toISOString().split('T')[0], level: 'HIGH', note: 'Duration and payment concentration signals detected' });
    }
    if (w.risk_level === 'CRITICAL') {
      const d = new Date(baseDate); d.setMonth(d.getMonth() + 14);
      entries.push({ date: d.toISOString().split('T')[0], level: 'CRITICAL', note: 'Multiple strong signals and vendor pattern confirmed' });
    }
    history[w.internal_work_key] = entries;
  });
  return history;
}

let _works = null;
let _expenditures = null;
let _riskHistory = null;

function getExpenditures() {
  if (!_expenditures) _expenditures = generateExpenditures();
  return _expenditures;
}

function getWorks() {
  if (!_works) {
    const { computeRisk } = require('../services/riskEngine');
    _works = worksRaw.map(w => {
      const mp = MPs.find(m => m.mp_id === w.mp_id) || {};
      const ida = IDAs.find(i => i.ida_id === w.ida_id) || {};
      const calamity = w.calamity_id ? calamities.find(c => c.calamity_id === w.calamity_id) : null;
      const enriched = { ...w, mp, ida, calamity };
      const risk = computeRisk(enriched, worksRaw, getExpenditures());
      return { ...enriched, ...risk };
    });
  }
  return _works;
}

function getRiskHistory() {
  if (!_riskHistory) _riskHistory = generateRiskHistory(getWorks());
  return _riskHistory;
}

function invalidateCache() { _works = null; _expenditures = null; _riskHistory = null; }

module.exports = {
  getMPs: () => MPs,
  getIDAs: () => IDAs,
  getCalamities: () => calamities,
  getVendors: () => {
    const works = getWorks();
    return vendors.map(v => {
      const vWorks = works.filter(w => w.vendor_ids.includes(v.vendor_id));
      const flagged = vWorks.filter(w => ['HIGH','CRITICAL'].includes(w.risk_level));
      const total = vWorks.reduce((s, w) => s + (w.total_expenditure_lakh || 0), 0);
      return { ...v, works_count: vWorks.length, flagged_works_count: flagged.length, total_amount_lakh: Math.round(total * 100) / 100, risk_flag: flagged.length > 1 };
    });
  },
  getWorks,
  getExpenditures,
  getRiskHistory,
  invalidateCache,
  appendWorks: (newWorks) => { _works = null; worksRaw.push(...newWorks); },
};
